FROM python:3.13.0a1-bookworm

RUN mkdir /logs

WORKDIR /app

COPY requirements-flask.txt requirements.txt 
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/

RUN pip install Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app", "--access-logfile", "/logs/access.log", "--error-logfile", "/logs/error.log", "--log-level", "debug"]